### PR TITLE
tweak(php 8.1): fix some php 8.1 issues

### PR DESCRIPTION
**Pull request by pschuele**

### CODE REVIEW

**Comment by hfig** [comment]
I don't oppose this generally. However, the change in version requirements for ``ramsey/uuid`` raises the minimum PHP version from 7.1 to 7.2. Was there a reason why you changed this? There's no change in any code that touches the ``uuid`` library.

**Comment by pschuele** [comment]
hi,
I updated 'ramsey/uuid' because the old version did not support php 8.1. but maybe there is a version which supports php 7.1 _and_ php 8.1?
I can remove the change in composer.json if you like.

**Comment by pschuele** [comment]
I updated the `ramsey/uuid` version requirement and rebased the PR branch.

**Comment by Zombaya** [comment]
Could this PR be merged?

The current code is currently generating deprecation notices in symfony projects and this PR solves these notices.

> Return type of Hfig\MAPI\OLE\Pear\DocumentElementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

> Return type of Hfig\MAPI\OLE\Pear\DocumentElementCollection::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

> ...

**Comment by hfig** [comment]
This PR will raise the project required PHP version to 8.0 (introduces the return pseudotype ``mixed``)

I **can** merge a PR that adds a return typed for everything except ``offsetGet()`` and attributes it as ``#[\ReturnTypeWillChange]``

Once this is done, I agree it's probably time so say bye to PHP7.x and make another release.

**Comment by m1ga** [comment]
would be great to have this merged. I've manually applied to return types so it won't show the deprecated messages (php 8.3). Works fine with php 8.1.2 and 8.3.12.

**Comment by hfig** [comment]
I've merged and tagged the other PR that maintains PHP 7.1 compatibility.

PHP7.4 is now so far out of support, shifting the minimum PHP version to 8.1 or 8.2 is not unreasonable. If someone wants to rebase this and do a general dependency update for a minimum PHP 8.1, I will release it as v2.0.0.

**Comment by pschuele** [comment]
oops, sorry - did not want to close the PR. a new one should created for the dependency update.

**Comment by hfig** [comment]
I don't disagree with closing it - better to open a new one rebased on the current master HEAD with a more comprehensive set of PHP 8.1 hinting/annotating improvements.

**Pull request closed without merging**
